### ISSUE TITLE
How to commit changes on form submit?

### ISSUE THREAD

**Issue by tute** [orbitjs/ember-orbit#16]
Right now, when I edit a model, I see on every change (including key presses), the following operations being enqueued:

![screen shot 2014-07-14 at 11 10 42 am](https://cloud.githubusercontent.com/assets/54260/3572529/2636484c-0b69-11e4-9f50-2ab60984e62b.png)

Right now I'm synchronizing memory with localStorage, so this is kind of free. But when I connect the JSON endpoint it will fire too many HTTP requests. How can I submit all the changes when the editing finishes (let's say, on form submit)?

**Comment by tute** [comment]
Hi @dgeb. Thanks for all your work on this!

I was wondering if there's been progress on the editing contexts feature.

Thanks again!

**Comment by dgeb** [comment]
Orbit now supports transactional contexts with immutable data (immutable.js makes creation of transactions extremely cheap).

ember-orbit wraps these capabilities in its own Store and Transaction classes.

**Comment by TheLooseCannon** [comment]
so what would be the correct method to use updateRecords so that orbit would identify the changes and only send patch requests for the updated values? 

this.store.update(t=>t.updateRecord()) is sending everything that i pass as attributes..
should i implement some method to check this before calling update, or does orbit provide this?

**Comment by dgeb** [comment]
@TheLooseCannon the most common approach used for forms is to fork a store, use the fork to handle form mutations, and then merge the fork back into the base store on submit. See https://github.com/orbitjs/ember-orbit#forking-and-merging-stores

**Comment by TheLooseCannon** [comment]
that worked pretty well. i loved that.@dgeb. Thanks for the help.

**Comment by TheLooseCannon** [comment]
does this method work with object attributes. i have certain attributes in in my data which are objects. is it possible to track the changes in these types of attributes too? 
i am also trying to figure out how if orbit would recognise relations if they are inside the object. 

something like
```js
data: {
attributes: {
       address: {
                   type: 'work',
                   address1: 'abc',
                   address2: 'xyz',
                   owner: 'owner-id',
                   residents: ['user1-id','user2-id']
            }
       }
}
```

or can you suggest a nice work around to handle this objects?

**Comment by dgeb** [comment]
@TheLooseCannon I'm glad that forking worked for you :)

In your example, the `address` object will be treated as a whole object that will be included in a `replaceAttribute` operation. If you want relationships to be recognized by Orbit so that it can manage inverses and such, I'd recommend that you normalize your schema - e.g. create models for `address`, `owner`, and `user` and break down the `address object. You can always build it back up at the serializer layer if your API requires this form.

Also, please ask how-to questions over in https://gitter.im/orbitjs/orbit.js  I'm liable to lose track of closed issues here, and this will allow others to pitch in as well.
