### ISSUE TITLE
Ember-Orbit model states

### ISSUE THREAD

**Issue by nayrban** [orbitjs/ember-orbit#202]
Hey, guys 

I have a question, there is something similar like states for models within ember-orbit (I mean something similar like ember-data has, for example saving, dirty, error, valid, etc)

**Comment by dgeb** [comment]
Hey @nayrban - thanks for the question! 

ember-orbit (and orbit in general) maintains a single state for each record in each source. Thus, each record can exist in as many states as there are sources. A record could be saved (or saving) to a backup source (e.g. indexeddb) while it is dirty relative to a remote source (e.g. JSON:API). A record could be edited in a store fork, and thus dirty, without affecting the state of the record in the main store (until the fork is merged). Because there is no practical limit to the number of sources that can exist in a single orbit application, there is no single state for each record (as identified by a `type` and `id`). It would be a real over-simplification to try to map all these dimensions down to a single value like ember-data does.

When talking about states from a practical matter, usually you're trying to reason about the state of mutations. Almost every state change is associated with a promise that will either resolve or fail. For edits of almost any complexity in orbit, I recommend isolating the changes in a store fork. You can then reason about the state of those changes as to the success of merging the fork. Even if you're directly calling `update` on a `store`, a promise will be returned that you can observe.

I hope this helps more than it confuses. Let me know if you have any questions as you give it a try.

**Comment by dgeb** [comment]
Giving this a close now for inactivity. Please open a new issue if you have fresh questions.
