### ISSUE TITLE
Merging a fork when using IndexedDb causes error

### ISSUE THREAD

**Issue by mfeckie** [orbitjs/ember-orbit#331]
I've been experimenting with ember-orbit and found that using a forked store results in an error when trying to merge it.

```ts
  forkUpdate = async () => {
    const fork = this.store.fork();
    await fork.update((q) =>
      q.replaceAttribute(this.args.userProfile, 'firstName', 'new name')
    );

    this.store.merge(fork);
  };
```

When the merge is executed in Chrome I get

`Uncaught (in promise) DOMException: Failed to execute 'put' on 'IDBObjectStore': class extends this {} could not be cloned.`

In Firefox it's similar `Uncaught (in promise) DOMException: The object could not be cloned.`

**Comment by dgeb** [comment]
Currently, the query builders used in ember-orbit are the same as in orbit, which confusingly means that they are unaware of ember-orbit models. Thus, when using `store.update` or `store.query` directly, you can't pass in models as arguments when identities are expected.

I believe that your issue will be resolved with the following change:

```diff
  forkUpdate = async () => {
    const fork = this.store.fork();
    await fork.update((q) =>
-      q.replaceAttribute(this.args.userProfile, 'firstName', 'new name')
+      q.replaceAttribute(this.args.userProfile.identity, 'firstName', 'new name')
    );

    this.store.merge(fork);
  };
```

Thus, the transform operation will just reference `{ type, id }` instead of the whole model, which orbit was attempting to clone (unsuccessfully).

This kind of defensive coding soon won't be needed. I'm adding the concept of "record normalizers" which interact with builders (see the WIP at https://github.com/orbitjs/orbit/pull/835/) which will translate records + identities from a dev-friendly form into one understandable by orbit. And then I'll create a custom normalizer for ember-orbit that will be fully model-aware. I expect this to be released in the next beta of v0.17.

**Comment by mfeckie** [comment]
Thanks so much for this.  I'll give it a try.

**Comment by dgeb** [comment]
As mentioned above, this has been addressed in recent betas through the introduction of a model-aware normalizer. You can freely use models when building queries and transforms and their identities will be extracted.
