### ISSUE TITLE
Best pattern for load+fork

### ISSUE THREAD

**Issue by ef4** [orbitjs/ember-orbit#347]
I'm using the store-beforequery-remote-query pattern as described in the demo app.

If I want to load an existing record and edit it in a forked store, what is the best way to do that?

I can do it manually like this:

```js
let store = this.owner.lookup('service:orbit');

let origOrg = await store.query((qb) =>
  qb.findRecord({ type: 'organization', key: 'remoteId', value: id })
);

let forked = store.fork();

let editableOrg = forked.cache.query((qb) =>
  qb.findRecord({ type: 'organization', id: origOrg.id })
);
```

But I feel like I may be missing a simpler solution that doesn't require saying `query()` twice.

For example, is there a way to adjust the strategies so that the forked in-memory store would fall back to the remote store? That does not seem to be inherited by the fork by default (which makes sense), but it means I need to first preload from remote into memory, then fork memory, then get my record out of memory.

**Comment by ef4** [comment]
I made little utilities to fork and merge one model at a time:

```js
export function fork(model) {
  let store = model.store;
  let forkedStore = store.fork();
  return forkedStore.cache.query((qb) => qb.findRecord(model));
}

export function merge(model) {
  let { store } = model;
  if (!store.forked) {
    throw new Error(`tried to save a model that is not in a forked store`);
  }
  return store.base.merge(store);
}
```

**Comment by dgeb** [comment]
You can access records in ember-orbit as

**Comment by dgeb** [comment]
Since v0.17.0-beta.11, you can access records in ember-orbit by [`RecordIdentity | RecordKeyValue | Model`](https://github.com/orbitjs/ember-orbit/blob/main/addon/-private/utils/model-aware-types.ts#L14) in a `findRecord` expression within a `query` or more concisely with the `findRecord` method on both the `Cache` and `Store`.

Given this, you could simplify your original code to the following:

```typescript
let store = this.owner.lookup('service:orbit');

let origOrg = await store.findRecord({ type: 'organization', key: 'remoteId', value: id });

let forked = store.fork();

let editableOrg = forked.cache.findRecord(origOrg);
```

And thanks for sharing your fork/merge utils! I'll be interested to know whether you continue to use them (vs. the code simplification above) and, if so, how they evolve over time.

**Comment by dgeb** [comment]
> For example, is there a way to adjust the strategies so that the forked in-memory store would fall back to the remote store? That does not seem to be inherited by the fork by default (which makes sense), but it means I need to first preload from remote into memory, then fork memory, then get my record out of memory.

It is possible to set up coordination strategies for your forked store so that it interacts with a remote source through the coordinator. I feel like this could work well if your goal is to isolate changes to the fork, without the intention of merging it back to its base. However, if your goal is to merge back to the base, you should consider calling the [rebase](https://github.com/orbitjs/orbit/blob/main/packages/%40orbit/memory/src/memory-source.ts#L359-L402) method on the fork to keep it in sync with its base (`rebase` is also available on the ember-orbit store btw, just pointing to the orbit code for better docs).

**Comment by ef4** [comment]
Thanks, that does make it more terse.

My takeaway is that I'm basically using the right pattern already, modulo minor stylistic improvements. Seems fine, just wanted to make sure I'm aligned with how you see the APIs.
