### ISSUE TITLE
Synchronous in-memory addRecord

### ISSUE THREAD

**Issue by ef4** [orbitjs/ember-orbit#348]
While continuing to port from ember-data, I was looking for a way to synchronously create an in-memory record, as a replacement for store.createRecord().

I found that the MemorySource's `cache` has a synchronous `update`, although it doesn't seem to be exposed through ember-orbit's wrapping `Cache` class. I tried using it like:

```js
let store = this.orbit.fork();
let identity = store.cache._sourceCache.update((t) =>
  t.addRecord({ type: 'organization' })
);
this.newOrg = store.cache.findRecord(identity.type, identity.id);
```

And this *nearly* works, except that when you try to merge this forked store back into the main one, it generates an `updateRecord` operation instead of an `addRecord` operation.

Should this work? Is there a different way? Should Orbit's `cache.update` get exposed through ember-orbit?

**Comment by dgeb** [comment]
I think you've hit upon a couple more improvements to be made here, @ef4.

> Should this work?

Yes, I believe it should. My first inclination was that `coalesceRecordOperations` was somehow replacing `updateRecord` with `addRecord` operations, but that does not seem to be the case [as per the tests](https://github.com/orbitjs/orbit/blob/main/packages/@orbit/records/test/record-operation-test.ts#L71-L92). I will attempt a reproduction and dig into why this transformation is happening.

> Should Orbit's `cache.update` get exposed through ember-orbit?

Again, yes, I believe so. The latest direction for ember-orbit is to more closely follow orbit's interfaces and expose them, albeit in a model-aware way (via the new normalizer). This should be straightforward.

**Comment by dgeb** [comment]
I took some time to work on this and consider it further.

I still agree with the need for `Cache#update`. #349 adds this method. I'll release this soon in a new beta. With this change, your code above is greatly simplified:

```diff
let store = this.orbit.fork();
- let identity = store.cache._sourceCache.update((t) =>
-   t.addRecord({ type: 'organization' })
- );
- this.newOrg = store.cache.findRecord(identity.type, identity.id);
+ this.newOrg = store.cache.update((t) =>
+   t.addRecord({ type: 'organization' })
+ );
```

As for the question about synchronous updates, I did not consider my original answer very carefully. What's happening here is actually not a bug but a result of a difference between Orbit's sources and caches.

Essentially an Orbit cache is like a directory of files and folders not under source control. Running `git init` creates a git repo based on this cache and `git add` selects what's being tracked. This git repo is analogous to an Orbit source that still references the same underlying "cache" and tracks changes to it. Notably, you can still add files and folders to the "cache" without affecting the git history, unless you explicitly make git aware of them.

Every Orbit `Source` has a `transformLog` which contains a history of transforms applied to that source. Every method that can affect this history is async, which allows for logs to be persisted async in buckets, and other sources to engage with events that result from changes.

On the other hand, every Orbit `RecordCache` simply contains a cache of records with no history. This cache can be updated, say to fill out a sparse set of records, but doing so will not generate a log of changes. This is why originally caches could only be patched with an array of operations, not transforms. I've since loosened this restriction, but perhaps it has muddied the waters.

All of this to say that, a store's fork is still a `Source`, which has a log. The log is used to determine the transforms that have been applied to the source since it's been forked. Any changes applied directly to its underlying cache will not be tracked as changes in the log.

I believe you're probably seeing changes come through as an `updateRecord` operation because you're applying updates to the forked store after the initial `addRecord` update that you've applied directly to the store's cache. Here's a [test](https://github.com/orbitjs/ember-orbit/blob/main/tests/integration/store-test.ts#L464-L470) you could use to experiment with this - if you call `forkedStore.cache.update` instead of `forkedStore.update`, you'll see that no transforms are applied on merge.

If possible, I'd recommend that you simply make updates async to forked sources. The promises just add a tick of async, but I know that can be annoying to program around some times.

If that's not possible, let me know the constraints around the problem and I will think on it some more. I think there's an elegant answer available here long term via a new architectural paradigm (think "branch" vs. "fork"). But there are surely plenty of hacks possible if you just need a quick workaround.

**Comment by dgeb** [comment]
I decided to go ahead and create that new paradigm in https://github.com/orbitjs/orbit/pull/873 to avoid churn after v0.17. I believe that it works well enough to make it the default mode of forking / merging.

I'll publish the next beta of `@orbit/memory` soon and then will circle back around to make some modifications to ember-orbit.

**Comment by dgeb** [comment]
As of ember-orbit v0.17.0-beta.15, which features tracking of sync updates in forked caches, this should now work:

```typescript
// sync `fork` of base store
let fork = store.fork();

// sync mutation of forked cache (could alternatively use the more verbose `update`)
let org = fork.cache.addRecord({ type: 'organization', name: 'Example' });

// async `merge`, which always returns results of coalesced transform in an array
let [ mergedOrg ] = store.merge(fork);
```
