### ISSUE TITLE
[Beta 15] Removed from cache errors

### ISSUE THREAD

**Issue by chbonser** [orbitjs/ember-orbit#359]
### Error
After upgrading from beta 14 to 15, I now see a lot of the following errors (relationship and attribute vary depending on the case):
```
The eventRecord record has been removed from its cache, so we cannot lookup the athlete hasOne relationship
The eventRecord record has been removed from its cache, so we cannot lookup the resultTimeSource attribute.
```

### Reproduction
This is a tricky one to reproduce but it occurs with a workflow roughly like this:
- Fork the store to display some info from a model. Let's call this the 'display fork'.
- Fork the store again to make some edits. Let's call this 'mutation fork'.
- In the mutation fork, delete the model displayed in display fork. 
- Merge mutation fork
- Rebase the display fork
- :boom: Error happens. (The UI driven by display fork does update to show the changes though)

@dgeb if this doesn't immediately make sense, let me know and I will try to make a reproducible test case

### Data Strategies
Store to remote sync, update, and query are all blocking.

### Versions
ember-orbit@0.17.0-beta.15

**Comment by dgeb** [comment]
@chbonser thanks for the detailed report. 

A few questions to narrow my focus:

* Can this be reproduced with just a store and no remote (i.e. no active coordination strategies)? 
* Can it be reproduced by directly without the mutation fork, but by simply deleting the record in the display fork and then rebasing?

**Comment by dgeb** [comment]
> The eventRecord record has been removed from its cache, so we cannot lookup the resultTimeSource attribute.

Models will display this error (or similar) when any data is accessed after they have been removed from their corresponding cache. I would expect that a model that's been deleted but is still rendered in the template to raise this exception.

Is the `eventRecord` in question connected with the display fork and deleted in the mutation fork? Does this error also happen if you don't do the rebase?

Sorry for all the questions. Feel free to answer with a reproduction if that would be simpler.

**Comment by chbonser** [comment]
Thanks @dgeb. I'll try to carve out some time later today to create a simplified reproduction.

**Comment by chbonser** [comment]
@dgeb I was able to reproduce this with a fairly simple setup. Please see the video in this PR https://github.com/forge512/orbit-demo/pull/1

**Comment by dgeb** [comment]
@chbonser thanks for the reproduction. 

What's happening here is that, as of https://github.com/orbitjs/ember-orbit/issues/359, the store became a `@tracked` property on the model. This was later changed to the cache, but effectively it's the same. When a record is removed from the cache, the model is disconnected, meaning it's no longer connected to a store / cache. If store / cache is tracked, then this invalidates every property on the model that was computed based on the store / cache.

I think that the assertions introduced in the field getters for #359 are correct, since they provide a useful error for why field values can not be retrieved from a disconnected model. However, as you show in this example, it's likely that the immediate invalidation of all fields on a model due to making store / cache tracked is a bit aggressive.

The question is whether any representation of a model should be immediately invalidated when that model is removed from its cache? I think the answer is likely "no" as your example shows. Otherwise, no resultsets could ever be considered "static".

I think we should probably remove cache tracking from models to eliminate this breaking change from v0.17.

**Comment by dgeb** [comment]
@chbonser sorry about that, I see what happened. I'll follow up with another PR soon with a fix and a better test.
