### ISSUE TITLE
Store.all doesn't load any records

### ISSUE THREAD

**Issue by opsb** [orbitjs/ember-orbit#52]
store.all returns a live record-array but it's initially populated by source.retrieve which hit's the source's cache rather than querying for records. This means that to load a live array of all records you have to do:

    store.find('type')
    var populatedLiveArrayForType = store.all('type');

Is this intentional? Perhaps it would be better to initialize the record-array with source.find('type') and then use retrieve from that point on?

On a more general note, given orbit's style I expected all, filter and find to return live arrays as standard (seems more in line with orbit.js' style). I can see that there might be value in having some live and others not live though but I think the API should make this distinction clearer.

**Comment by dgeb** [comment]
This is definitely intentional. `find` is asynchronous and returns a static record array. `all` is synchronous and returns a live record array. This allows for maximum flexibility and control.

When combined, you can return a live record array only after `find` completes. For instance: `return store.find('type').then(function() { return store.all('type'); });`. It's also valid to just return the result from `find` if you want to capture all the records of a type *at a particular moment in time*. If `find` always returned `all`, then this distinction wouldn't be possible. Another valid use case is to bind a collection to the `all` live array - you don't need to immediately trigger the async `find` to do so.

I'm not saying that I'm opposed to adding convenience methods (`findAll` perhaps?) that merge functionality, but I want to keep the distinction as well.

[This section](https://github.com/orbitjs/ember-orbit#stores) of the README clarifies which methods are synchronous and which are asynchronous. All the synchronous methods provide immediate access to a store's current contents, while all the asynchronous methods flow through Orbit's requestable interface.

**Comment by opsb** [comment]
That does seem reasonable. I suspect I would use findAll far more often than all so yes that would be a nice addition. I'm working on a firebase Source at the moment but I'd be happy to put a PR together once I've got that out the way.

**Comment by dgeb** [comment]
You can now query a store (`store.query`) to engage with an Orbit Coordinator and remote sources (if configured). Or you can query a store's cache (`store.cache.query`) to only get results presently in memory.
