### ISSUE TITLE
Don't include records in links until they're loaded

### ISSUE THREAD

**Issue by opsb** [orbitjs/ember-orbit#83]
When links are populated any records that haven't been loaded yet are represented as a stub (stored in the identity map so they can be easily populated later). Because the records haven't been populated yet they don't have any properties so when a link is rendered as a list for example these records show up as gaps. 

I suggest that records in the identity map should track whether or not they've been loaded. The link can then filter out records that haven't been loaded yet, only showing them once their status changes to loaded.

**Comment by dgeb** [comment]
Wow, this is an ancient issue! Sorry for delaying with a response @opsb. It's been a while, hope all is well :)

---

The concept of "loaded" is a bit nebulous in an orbit cache since data can come from any source. Records may have some data populated due to inverse relationships created by cache processors. Therefore, a simple check for the presence of any data is not sufficient to know that it was populated through particular means.

The current recommendation to check whether a record has been loaded is to establish criteria for your app as to what that means: for instance, a check for the presence of a particular field such as a timestamp that is assigned by the server.
